apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          command: ["python", "-c", "import http.server; print('{{ .Values.appMessage }}'); http.server.test(HandlerClass=http.server.SimpleHTTPRequestHandler, port=8080)"]
          ports:
            - containerPort: 8080
              protocol: TCP