FROM ubuntu:latest

# Ошибка 1: Запуск от root (по умолчанию)
# Ошибка 2: Использование latest тега
# Ошибка 3: Неэффективные слои (множественные RUN)

RUN apt-get update
RUN apt-get install -y python3 python3-pip
COPY . /app
WORKDIR /app

CMD [python3, app.py]
