apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-web-deployment
spec:
  replicas: 2 # Запустим сразу две копии для надежности
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
      - name: python-web
        image: python:3.11-slim
        command: ["python", "-c", "import http.server; print('Started'); http.server.test(HandlerClass=http.server.SimpleHTTPRequestHandler, port=8080)"]
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  selector:
    app: web-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort